### ISSUE TITLE
add support for lufs/lkfs

### ISSUE THREAD

**Issue by gamerseye123** [Arpapiemonte/openoise-meter#11]
Add the option to change dB to lufs, which are a more accurate unit for loudness

https://en.m.wikipedia.org/wiki/LKFS

**Comment by Arpapiemonte** [comment]
Hi, thanks for the suggestion.
OpeNoise is created in according the measurement and assessment of environmental noise, as indicated in the [ISO 1996-1:2016](https://www.iso.org/standard/59765.html).
Any contribution to the code is welcome to extent the compatibility.
Thanks again!
