### ISSUE TITLE
Play Store "app is not available for your device"

### ISSUE THREAD

**Issue by 4rz0** [Arpapiemonte/openoise-meter#2]
Trying to install this on my Galaxy S20 Ultra, but the search in the Play Store doesn't even return the app, and on the webpage it's listed as "app is not available for your device".
I guess this has something to do with Android versions (The S20 is on Android 13).

**Comment by losciur** [comment]
Hi @4rz0,
yes, this is due to the new Android 13 version.
In a couple of weeks we will enable to publish a new major release of OpeNoise that (obviously) will be compatible with Android 13.

**Comment by IzzySoft** [comment]
Would you consider publishing the APK outside of Play (e.g. attached to [Releases](https://github.com/Arpapiemonte/openoise-meter/releases) here) for those having no access to Google's walled garden? Thanks in advance!

**Comment by Arpapiemonte** [comment]
Hi @IzzySoft  at this moment we are not considering to publish tha app outside the official store, thanks for the suggestion.

**Comment by IzzySoft** [comment]
That's a pity, as that excludes everyone without access to Play (and as this issue shows even to some *with* access to it). To give you an idea who that might be:

* folks who cut their ties for reasons (privacy etc) and running on de-googled devices (like me)
* folks on devices coming without the GApps (AFAIK e.g. Huawei devices)
* folks in countries with internet censorship (like "great firewall" – but it's not "only China")

And before you point to work-arounds getting the app from Play: some of those require technical skills not everyone has (like getting around those "great firewalls"), others trust in places some of us simply do not have (Google & Co, or other apps/sites needed to obtain the APK – where getting it from some places would also entail risks for you: you might get issues/reports for 3rd-party-builds). So it would be ideal if your app would be available e.g. via [F-Droid](https://f-droid.org/), or (not as good as that) via [my repo](https://apt.izzysoft.de/fdroid) (which would require an APK available as outlined, but then offers additional measurements like having the APK automatically scanned by VirusTotal and some other scanners, pointing out the results). Both places also make your app easier to be discovered by the groups of people outlined above and give an added "verified by" trust – so it would be a win-win.

If you don't mind the question: what keeps you from publishing your app outside Play? Did you decide to leave all the key handling to Google and thus do not have a private key to sign the APK with? Or is it just that (up to now) you thought it's too much trouble for too little good? In the latter case I can assure you it's not: it would show that you really care about making your FOSS app available to FOSS lovers, and thus bring you "extra points" even – apart from the win-win I just outlined :wink:

That said: No offense meant, and no pressure. If you still say "no" I'll accept that and not push it further. I just wanted to make sure you have a "most complete picture".
