### ISSUE TITLE
Huge error occurred after updating to version 3.0

### ISSUE THREAD

**Issue by mercury233** [Arpapiemonte/openoise-meter#3]
I'm in the same room which I think its noise is about 50 db.
The old app can show the correct value but the new one can't.

![image](https://github.com/Arpapiemonte/openoise-meter/assets/13391795/4d369382-d4fb-4144-a573-34bd5086bc9a)
![image](https://github.com/Arpapiemonte/openoise-meter/assets/13391795/de49bd6d-79e5-41dd-9d9d-5cc03498e65d)

**Comment by Arpapiemonte** [comment]
Hi @mercury233 , 
did you calibrate the new app by comparing the noise level with a professional noise meter?
After the update, you have to calibrate the app with a new value, the old value is not correct.

**Comment by mercury233** [comment]
In the old version I didn't change the calibration value which is 0, and the app showed a value that is closer to the correct value.
I don't have a real noise meter so I can't measure it.

**Comment by Arpapiemonte** [comment]
I'm sorry but this was an usage error also with the old app, using the app (old or new) without compare the levels with a real noise meter is not recommended and the levels can be very different from the reality.
Also the professional noise meter needs to be calibrated.
All this informations are written in the warning page of the apps.

**Comment by mercury233** [comment]
OK I got it. Anyway I hope you make it clear that there may be dozens of errors from the actual decibel value, and let the user go to the setting page in the first launch.

**Comment by twest820** [comment]
I agree this is unforced and will be opening issues on a couple other regressions in OpeNoise 3.0.

- If a professional meter was readily available there presumably wouldn't be need to use OpeNoise. So the developer's apparent assumption recalibrating OpeNoise with a professional meter is no big deal is strange, particularly as the typical user discovery here will be to open OpeNoise to take a measurement only to find readings have shifted by over 20 dB(A). This is particularly problematic if you've traveled to a work site and then have to drop everything you were planning to do to recal.
- The developer's assumption users burn the cal value into OpeNoise is substantially incorrect. It's often best practice in data logging to log the raw data coming off the sensor—OpeNoise in this case—and apply the calibration separately. Being able to put a cal offset in OpeNoise is a great convenience feature for some users but the idea everyone must use the app in this one way creates forces unnecessary complexity onto users in cases where data gets reprocessed with an improved cal.

**Comment by Arpapiemonte** [comment]
First point.
No device (smartphone/tablet) can guarantee you a noise measurement without a calibration. Even professional sound level meters themselves must be calibrated. Italian noise regulations oblige, when making a fiscal measurement, to calibrate the professional sound level meter **before** and **after** the measurement, for each measurement! In addition, every two years, the professional sound level meter must be sent to a certified calibration center for further inspection and more precise calibration.
Clearly, a simple mobile device, whose goal is certainly not to make noise measurements, cannot automatically measure noise correctly without calibration. Moreover, any other serious and honest app requires calibration.

Second point.
If you want to get the raw data without calibrating the device, you may very well do so by leaving the calibration values at zero.
