### ISSUE TITLE
first 10–20 samples in a measurement now appear to be commonly erroneous

### ISSUE THREAD

**Issue by twest820** [Arpapiemonte/openoise-meter#5]
I'm seeing this pattern over and over again measuring in environments with stable noise levels in OpeNoise 3.0.3: often, but not always, initial values in a measurement will be ~0.3–0.9 dB(A) lower than what LAeq(1s) settles to after several seconds of averaging. This happens both when starting a new measurement and when hitting reset. In more extreme cases there can be a 5–10 dB(A) overshoot and then measurement settles down. This is problem as the average value gets corrupted and, instead of reading the average OpeNoise reports, a corrected average has to be estimated manually from the display or reprocessed from saved data. In cases where the measurement protocol's a 10 or 15 second average it's easily the case the entire measurement ends up apparently corrupt, rendering OpeNoise no longer usable.

Could we please have an option to revert to the pre-3.0 measurement method until 3.0's implementation is more reliable? I understand from comments in other issues pre-3.0 is maybe not considered to be correct. However, it's implausible that it's more incorrect than 3.0.3's current behavior.

**Comment by Arpapiemonte** [comment]
Hi,
thanks for the issue.
We will do some targeted testing to study this behavior.
Consider that if the error is in the 1 dB range, it might be acceptable and within the measurement uncertainty.
Could you send us a measurement file to better understand the behavior?
Thank you
