### ISSUE TITLE
lower limit of sound level axis range cannot be set below 0 dB(A)

### ISSUE THREAD

**Issue by twest820** [Arpapiemonte/openoise-meter#7]
In #3's discussion, leaving OpeNoise's calibration setting at 0 dB(A) came up in the context of raw or (equivalently, uncalibrated) data and ended up being suggested for certain workflows. A difficulty with this approach is that, as OpeNoise 3.0.x produces readings 20+ dB(A) lower than OpeNoise 2.0.3, measured dB(A) values now easily go negative. Since display cuts off 0 dB(A), 3.0.x makes monitoring data as it's being collected from quiet settings more difficult. Traces are sometimes moved up and drawn at 0 dB(A) at the bottom of the graph, other times they're not drawn at all.

A trivial workaround's to monitor the one second reading's text display. It will read out -3.4 dB(A) or such, which accomplishes all basic purposes easily enough. But it is pretty nice to have the visual context provided by the measurement graph.

Since there's already adjustable high and low limits on the display range slider hopefully it's a small edit to allow the lower limit to go to -20 dB(A). This syncs the UX with 3.0.x's changes in measurement values, though leaving the default lower limit at 0 dB(A) seems fine to me.

(Italian's not one of the five languages I'm familiar with and I'm not set up for Android app development but, from a look at the code, I think this might be in the src/app/pages/settings bits around `assi` and `modalRange`.)

**Comment by Arpapiemonte** [comment]
Ok, we can add the possibility to set the low limit to -20 dB(A) in the next release.
Thanks
