### ISSUE TITLE
timestamps are logged a fixed localized format

### ISSUE THREAD

**Issue by twest820** [Arpapiemonte/openoise-meter#9]
OpeNoise' current date and time format in measurement files seems to be fixed as `dd/MM/yyyy(;|\.|\|)HH:MM:ss[.fff]`, which doesn't follow .csv format conventions for other locales where the order of date components may differ

This is a minor thing and I'd expect most users working with saved measurements to know how to deal with it. For completeness, though, the current settings for configuring the measurement file format should probably also offer to change the year-month-day order. Since users can make localized choices for the extension, field separator, and decimal separator it feels incomplete the date format can't also be localized,

Don't know if anybody'd use it (well, besides me, anyways) but an option for ISO 8601 datetimes might also be worth considering.

**Comment by Arpapiemonte** [comment]
Ok, we add this option in a future release.
